name: BE-CI

on:
    pull_request:
        branches:
            - main
        paths:
            - 'starter/backend/**'
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: pip install pipenv
              
            - name: Install project dependencies
              run: pipenv install
              
            - name: Run lint
              run: pipenv run lint
              working-directory: starter/backend
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: pip install pipenv
              
            - name: Install project dependencies
              run: pipenv install
              
            - name: Run tests
              run: pipenv run test
              working-directory: starter/backend

    build:
        runs-on: ubuntu-latest
        needs: [lint, test]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build Docker image
              run: docker build -t movie-picture-backend ./starter/backend